name: One open PR per ticket

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  enforce:
    runs-on: self-hosted
    steps:
      - name: Close PR if another open PR exists for same ticket
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          API="${{ gitea.server_url }}/api/v1"
          OWNER="${{ gitea.repository.owner }}"
          REPO="${{ gitea.repository.name }}"
          PR_INDEX="${{ gitea.event.pull_request.index }}"
          HEAD_REF="${{ gitea.event.pull_request.head.ref }}"

          # Ticket = digits after "feature/" (feature/123-foo -> 123)
          TICKET=$(printf '%s' "$HEAD_REF" | sed -n 's|^feature/\([0-9][0-9]*\)-.*|\1|p')
          [ -z "$TICKET" ] && exit 0

          # Find another OPEN PR with same ticket in head branch name
          PRS=$(curl -s -H "Authorization: token $ZDS_ACTION_TOKEN" \
            "$API/repos/$OWNER/$REPO/pulls?state=open&limit=99&page=1")

          DUP=$(echo "$PRS" | jq -r --arg t "$TICKET" --arg me "$PR_INDEX" '
            .[]
            | select((.number|tostring) != $me)
            | select((.head.ref // "") | test("^feature/" + $t + "-"))
            | .number
          ' | head -n1)

          [ -z "$DUP" ] && exit 0

          echo "Duplicate ticket PR: ticket $TICKET already has open PR #$DUP"
          exit 1
