name: One open PR per ticket

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  enforce:
    runs-on: self-hosted
    steps:
      - name: Close PR if another open PR exists for same ticket
        env:
          ZDS_ACTIONS_TOKEN: ${{ secrets.ZDS_ACTIONS_TOKEN }}
        run: |
          API="${{ gitea.server_url }}/api/v1"
          OWNER="${GITHUB_REPOSITORY%%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          PR_INDEX="$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")"
          HEAD_REF="$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")"

          # Ticket = digits after "feature/" (feature/123-foo -> 123)
          TICKET=$(printf '%s' "$HEAD_REF" | sed -n 's|^feature/\([0-9][0-9]*\)-.*|\1|p')
          [ -z "$TICKET" ] && exit 0

          # Find another OPEN PR with same ticket in head branch name
          URL="$API/repos/$OWNER/$REPO/pulls?state=open&limit=100&page=1"
          PRS=$(curl -fsS -H "Authorization: token $ZDS_ACTIONS_TOKEN" "$URL") || {
            echo "API fetch failed: $URL"
            exit 1
          }

          DUP=$(echo "$PRS" | jq -r --arg t "$TICKET" --arg me "$PR_INDEX" '
            .[]
            | select((.number|tostring) != $me)
            | select((.head.ref // "") | test("^feature/" + $t + "-"))
            | .number
          ' | head -n1)

          echo "DEBUG: PR_INDEX=$PR_INDEX; first list item id/number=$(echo "$PRS" | jq -r '.[0] | "\(.id)/\(.number)"')"

          [ -z "$DUP" ] && exit 0

          echo "Duplicate ticket PR: ticket $TICKET already has open PR #$DUP"
          exit 1
